### ISSUE TITLE
gdt-modAPI doesn't exist on npm

### ISSUE THREAD

**Issue by Trophonix** [greenheartgames/gdt-modAPI#16]
```
[lucas@lucas-linux gdt-mod-test]$ npm i gdt-modAPI
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/gdt-modAPI - Not found
npm ERR! 404 
npm ERR! 404  'gdt-modAPI@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404  2. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lucas/.npm/_logs/2019-01-22T05_08_30_259Z-debug.log
```

I'll try installing it from the repo, but it'd be cool if it could be on the registry?

Edit: I tried installing it with the git repo and got this
```
10 verbose stack Error: premature close
10 verbose stack     at PassThrough.onclose (/usr/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
10 verbose stack     at PassThrough.emit (events.js:193:15)
10 verbose stack     at emitCloseNT (internal/streams/destroy.js:59:8)
10 verbose stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

Guess I will try manually downloading the repo and adding it as a dependency! 

Edit 2:
Ok now that I'm looking more into this, it seems like something is wrong with the package.json and the wiki.. The "id" field isn't a thing in npm (so I guess that's for you to use?) and the "name" field is meant to be a unique URL-valid string for identification purposes.. So putting "gdt-modAPI" in package.json won't work, that's not the name of the package. Maybe this was made on an early version of NPM? Or I'm really confused.

**Comment by patrickklug** [comment]
The package.json might look similar to a npm module but the game and modding api don't have anything to do with npm. It's all proprietary to the game. package.json is just used for the game to discover mods and load/display them correctly.
